### ISSUE TITLE
Compiling fails on archlinux

### ISSUE THREAD

**Issue by SanskritFritz** [tarmack/Mangonel#3]
-- The C compiler identification is GNU 4.7.0
-- The CXX compiler identification is GNU 4.7.0
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Looking for Q_WS_X11
-- Looking for Q_WS_X11 - found
-- Looking for Q_WS_WIN
-- Looking for Q_WS_WIN - not found.
-- Looking for Q_WS_QWS
-- Looking for Q_WS_QWS - not found.
-- Looking for Q_WS_MAC
-- Looking for Q_WS_MAC - not found.
-- Found Qt4: /usr/bin/qmake (found version "4.8.1") 
-- Found Qt-Version 4.8.1 (using /usr/bin/qmake)
-- Looking for XOpenDisplay in /usr/lib/libX11.so;/usr/lib/libXext.so;/usr/lib/libXft.so;/usr/lib/libXau.so;/usr/lib/libXdmcp.so;/usr/lib/libXpm.so
-- Looking for XOpenDisplay in /usr/lib/libX11.so;/usr/lib/libXext.so;/usr/lib/libXft.so;/usr/lib/libXau.so;/usr/lib/libXdmcp.so;/usr/lib/libXpm.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/libX11.so
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found.
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found OpenSSL: /usr/lib/libssl.so
-- Looking for _POSIX_TIMERS
-- Looking for _POSIX_TIMERS - found
-- Found Automoc4: /usr/bin/automoc4 
-- Found Perl: /usr/bin/perl (found version "5.14.2") 
-- Found Phonon: /usr/include 
-- Performing Test _OFFT_IS_64BIT
-- Performing Test _OFFT_IS_64BIT - Success
-- Performing Test HAVE_FPIE_SUPPORT
-- Performing Test HAVE_FPIE_SUPPORT - Success
-- Performing Test __KDE_HAVE_W_OVERLOADED_VIRTUAL
-- Performing Test __KDE_HAVE_W_OVERLOADED_VIRTUAL - Success
-- Performing Test __KDE_HAVE_GCC_VISIBILITY
-- Performing Test __KDE_HAVE_GCC_VISIBILITY - Success
-- Found KDE 4.8 include dir: /usr/include
-- Found KDE 4.8 library dir: /usr/lib
-- Found the KDE4 kconfig_compiler preprocessor: /usr/bin/kconfig_compiler
-- Found automoc4: /usr/bin/automoc4
-- Configuring done
-- Generating done
-- Build files have been written to: /Common/Builds/aur/mangonel-git/src/Mangonel
[  5%] [ 11%] Generating Units.moc
Generating Mangonel.moc
[ 16%] Generating Label.moc
[ 22%] Generating Config.moc
[ 27%] Generating Applications.moc
[ 33%] Generating Paths.moc
[ 38%] Generating Shell.moc
[ 44%] Generating Calculator.moc
Scanning dependencies of target mangonel
[ 50%] [ 55%] Building CXX object CMakeFiles/mangonel.dir/Mangonel.o
Building CXX object CMakeFiles/mangonel.dir/Label.o
/Common/Builds/aur/mangonel-git/src/Mangonel/Label.cpp:6:1: warning: unused parameter ‘parent’ [-Wunused-parameter]
/Common/Builds/aur/mangonel-git/src/Mangonel/Mangonel.cpp:247:6: warning: unused parameter ‘event’ [-Wunused-parameter]
/Common/Builds/aur/mangonel-git/src/Mangonel/Mangonel.cpp:259:6: warning: unused parameter ‘object’ [-Wunused-parameter]
/Common/Builds/aur/mangonel-git/src/Mangonel/Mangonel.cpp:289:1: warning: unused parameter ‘parent’ [-Wunused-parameter]
/Common/Builds/aur/mangonel-git/src/Mangonel/Mangonel.cpp: In member function ‘void IconView::moveItems(IconView::direction)’:
/Common/Builds/aur/mangonel-git/src/Mangonel/Mangonel.cpp:370:20: error: ‘usleep’ was not declared in this scope
/Common/Builds/aur/mangonel-git/src/Mangonel/Mangonel.cpp:379:20: error: ‘usleep’ was not declared in this scope
/Common/Builds/aur/mangonel-git/src/Mangonel/Mangonel.cpp:387:20: error: ‘usleep’ was not declared in this scope
[ 61%] Building CXX object CMakeFiles/mangonel.dir/Config.o
make[2]: **\* [CMakeFiles/mangonel.dir/Mangonel.o] Error 1
make[2]: **\* Waiting for unfinished jobs....
make[1]: **\* [CMakeFiles/mangonel.dir/all] Error 2
make: **\* [all] Error 2

**Comment by sandsmark** [comment]
fixed by adding the unistd.h include.
fixed here: https://github.com/sandsmark/Mangonel/commit/b57942fc8a2292fc4ff33ea5903cb744ace87909

**Comment by SanskritFritz** [comment]
Woa, great, thanks! Put up a pull request :)

**Comment by sandsmark** [comment]
already did.
